FROM golang:latest as builder
WORKDIR /go-http-hello-world/
RUN mkdir -p /go/src/golang.org/ 
COPY files/net /go/src/golang.org/
ADD https://raw.githubusercontent.com/geetarista/go-http-hello-world/master/hello_world/hello_world.go ./hello_world.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM scratch
COPY --from=builder /go-http-hello-world/app .
CMD ["./app"]

